engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
ratings:
  paths:
  - "pyt/*"
  - "**.py"
exclude_paths:
- "example/**"
- "profiling/**"
- "tests/**"
- "LICENSE"
- "**/trigger_definitions/*"
- "**.cfg"
- "**.csv"
- "**.in"
- "**.md"
- "**.png"
- "**.pyt"
- "**.rst"
- "**.sh"
- "**.txt"
