language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
script:
  - python -m tests
  - coverage run -m tests
after_script:
  - codeclimate-test-reporter
